# generated by datamodel-codegen:
#   filename:  API
#   timestamp: 2024-02-27T19:34:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, constr

from .Entity import Entity


class ApiVersion(Enum):
    backstage_io_v1alpha1 = "backstage.io/v1alpha1"
    backstage_io_v1beta1 = "backstage.io/v1beta1"


class Kind(Enum):
    API = "API"


class Spec(BaseModel):
    type: constr(min_length=1) = Field(
        ...,
        description="The type of the API definition.",
        examples=["openapi", "asyncapi", "graphql", "grpc", "trpc"],
    )
    lifecycle: constr(min_length=1) = Field(
        ...,
        description="The lifecycle state of the API.",
        examples=["experimental", "production", "deprecated"],
    )
    owner: constr(min_length=1) = Field(
        ...,
        description="An entity reference to the owner of the API.",
        examples=["artist-relations-team", "user:john.johnson"],
    )
    system: Optional[constr(min_length=1)] = Field(
        None, description="An entity reference to the system that the API belongs to."
    )
    definition: constr(min_length=1) = Field(
        ...,
        description="The definition of the API, based on the format defined by the type.",
    )


class Model(Entity):
    model_config = ConfigDict(
        extra="allow",
    )
    apiVersion: Optional[ApiVersion] = None
    kind: Optional[Kind] = None
    spec: Spec
