# generated by datamodel-codegen:
#   filename:  Domain
#   timestamp: 2024-02-27T19:48:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

from backstage_catalog_client.entity.Entity import Entity


class ApiVersion(Enum):
    backstage_io_v1alpha1 = "backstage.io/v1alpha1"
    backstage_io_v1beta1 = "backstage.io/v1beta1"


class Spec(BaseModel):
    owner: str = Field(
        ...,
        description="An entity reference to the owner of the component.",
        examples=["artist-relations-team", "user:john.johnson"],
        min_length=1,
    )


class Domain(Entity):
    model_config = ConfigDict(
        extra="allow",
    )
    apiVersion: Optional[ApiVersion] = None
    kind: Literal["Domain"] = "Domain"
    spec: Spec
