# generated by datamodel-codegen:
#   filename:  Entity
#   timestamp: 2024-02-27T19:48:38+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field

from backstage_catalog_client.entity import EntityMeta, common

# TODO: custom serializers: https://docs.pydantic.dev/latest/api/functional_serializers/#pydantic.functional_serializers.model_serializer


class Entity(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    apiVersion: str = Field(
        ...,
        description="The version of specification format for this particular entity that this is written against.",
        examples=["backstage.io/v1alpha1", "my-company.net/v1", "1.0"],
        min_length=1,
    )
    kind: str = Field(
        ...,
        description="The high level entity type being described.",
        examples=[
            "API",
            "Component",
            "Domain",
            "Group",
            "Location",
            "Resource",
            "System",
            "Template",
            "User",
        ],
        min_length=1,
    )
    metadata: EntityMeta.Model
    spec: Optional[dict[str, Any]] = Field(None, description="The specification data describing the entity itself.")
    relations: list[common.Relation] = Field([], description="The relations that this entity has with other entities.")
