# generated by datamodel-codegen:
#   filename:  Location
#   timestamp: 2024-02-27T19:48:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field, RootModel

from backstage_catalog_client.entity.entity import Entity


class ApiVersion(Enum):
    backstage_io_v1alpha1 = "backstage.io/v1alpha1"
    backstage_io_v1beta1 = "backstage.io/v1beta1"


class Kind(Enum):
    Location = "Location"


class Target(RootModel[str]):
    root: str = Field(
        ...,
        examples=[
            "./details/catalog-info.yaml",
            "http://github.com/myorg/myproject/org-data-dump/catalog-info-staff.yaml",
        ],
        min_length=1,
    )


class Presence(Enum):
    required = "required"
    optional = "optional"


class Spec(BaseModel):
    type: Optional[str] = Field(
        None,
        description="The single location type, that's common to the targets specified in the spec. If it is left out, it is inherited from the location type that originally read the entity data.",
        examples=["url"],
        min_length=1,
    )
    target: Optional[str] = Field(
        None,
        description="A single target as a string. Can be either an absolute path/URL (depending on the type), or a relative path such as ./details/catalog-info.yaml which is resolved relative to the location of this Location entity itself.",
        examples=["./details/catalog-info.yaml"],
        min_length=1,
    )
    targets: Optional[list[Target]] = Field(
        None,
        description="A list of targets as strings. They can all be either absolute paths/URLs (depending on the type), or relative paths such as ./details/catalog-info.yaml which are resolved relative to the location of this Location entity itself.",
    )
    presence: Optional[Presence] = Field(
        "required",
        description="Whether the presence of the location target is required and it should be considered an error if it can not be found",
        examples=["required"],
    )


class Location(Entity):
    apiVersion: ApiVersion = ApiVersion.backstage_io_v1beta1
    kind: Literal["Location"] = "Location"
    spec: Spec

    # maybe a bit of hack, but we want some default values to continue to show up when calling model.model_dump()
    def model_post_init(self):
        self.__pydantic_fields_set__.add("kind")
        self.__pydantic_fields_set__.add("apiVersion")
