# generated by datamodel-codegen:
#   filename:  Resource
#   timestamp: 2024-02-27T19:48:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field, RootModel

from backstage_catalog_client.entity.Entity import Entity


class ApiVersion(Enum):
    backstage_io_v1alpha1 = "backstage.io/v1alpha1"
    backstage_io_v1beta1 = "backstage.io/v1beta1"


class Kind(Enum):
    Resource = "Resource"


class DependsOnItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class Spec(BaseModel):
    type: str = Field(
        ...,
        description="The type of resource.",
        examples=["database", "s3-bucket", "cluster"],
        min_length=1,
    )
    owner: str = Field(
        ...,
        description="An entity reference to the owner of the resource.",
        examples=["artist-relations-team", "user:john.johnson"],
        min_length=1,
    )
    dependsOn: Optional[list[DependsOnItem]] = Field(
        None,
        description="An array of references to other entities that the resource depends on to function.",
    )
    system: Optional[str] = Field(
        None,
        description="An entity reference to the system that the resource belongs to.",
        min_length=1,
    )


class Resource(Entity):
    apiVersion: ApiVersion = ApiVersion.backstage_io_v1beta1
    kind: Literal["Resource"] = "Resource"
    spec: Spec

    # maybe a bit of hack, but we want some default values to continue to show up when calling model.model_dump()
    def model_post_init(self):
        self.__pydantic_fields_set__.add("kind")
        self.__pydantic_fields_set__.add("apiVersion")
