# generated by datamodel-codegen:
#   filename:  System
#   timestamp: 2024-02-27T19:48:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field

from backstage_catalog_client.entity.Entity import Entity


class ApiVersion(Enum):
    backstage_io_v1alpha1 = "backstage.io/v1alpha1"
    backstage_io_v1beta1 = "backstage.io/v1beta1"


class Kind(Enum):
    System = "System"


class Spec(BaseModel):
    owner: str = Field(
        ...,
        description="An entity reference to the owner of the component.",
        examples=["artist-relations-team", "user:john.johnson"],
        min_length=1,
    )
    domain: Optional[str] = Field(
        None,
        description="An entity reference to the domain that the system belongs to.",
        examples=["artists"],
        min_length=1,
    )


class System(Entity):
    apiVersion: ApiVersion = ApiVersion.backstage_io_v1beta1
    kind: Literal["System"] = "System"
    spec: Spec

    # maybe a bit of hack, but we want some default values to continue to show up when calling model.model_dump()
    def model_post_init(self):
        self.__pydantic_fields_set__.add("kind")
        self.__pydantic_fields_set__.add("apiVersion")
